# Site
name: "TechWritersNation.com"
title: "Home | TechWritersNation.com "
description: "Love Writing? Looking for a career to be Technical writer? Find the ultimate guidance in my blog to find the basic, career related and advanced stuff in the world of Technical communication industry. "
meta_description: "Love Writing? Looking for a career to be Technical writer? Find the ultimate guidance in my blog to find the basic, career related and advanced stuff in the world of Technical communication industry."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: '/'
email: 'nazeerbai@gmail.com'
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  Nazurudeen:
    name: Nazurudeen
    display_name: Nazurudeen
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: nazeerbai@gmail.com
    web:
    linkedin: https://www.linkedin.com/in/nazurudeen-j-09529118/
    description: "Nazurudeen J. is the Administrator of all the content writers working at TechWritersNation.com."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Other
markdown: kramdown
highlighter: rouge
